### **Mounting the google drive to the colab environment:**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
%cd '/content/drive/MyDrive/Assessment_Final_Data'

/content/drive/MyDrive/Assessment_Final_Data

# TASK 1: DATA HANDLING

## LOADING THE DATASET

In [4]:
%ls

combined_output.csv
PRSA_Data_Dingling_20130301-20170228.csv
PRSA_Data_Shunyi_20130301-20170228.csv
PRSA_Data_Tiantan_20130301-20170228.csv
PRSA_Data_Wanliu_20130301-20170228.csv
PRSA_Data_Wanshouxigong_20130301-20170228.csv

In [5]:
import pandas as pd
import glob

# Get all CSV files in the folder
csv_files = glob.glob("/content/drive/MyDrive/Assessment_Final_Data/*.csv")
csv_files

['/content/drive/MyDrive/Assessment_Final_Data/PRSA_Data_Dingling_20130301-20170228.csv',
 '/content/drive/MyDrive/Assessment_Final_Data/PRSA_Data_Wanshouxigong_20130301-20170228.csv',
 '/content/drive/MyDrive/Assessment_Final_Data/PRSA_Data_Tiantan_20130301-20170228.csv',
 '/content/drive/MyDrive/Assessment_Final_Data/PRSA_Data_Shunyi_20130301-20170228.csv',
 '/content/drive/MyDrive/Assessment_Final_Data/PRSA_Data_Wanliu_20130301-20170228.csv',
 '/content/drive/MyDrive/Assessment_Final_Data/combined_output.csv']

## COMBINING ALL THE DATASETS TO ONE DATAFRAME

In [20]:
# Read and combine all CSV files
combined_df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)
combined_df

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,3.0,NaN,200.0,82.0,-2.3,1020.8,-19.7,0.0,E,0.5,Dingling
1,2,2013,3,1,1,7.0,7.0,3.0,NaN,200.0,80.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Dingling
2,3,2013,3,1,2,5.0,5.0,3.0,2.0,200.0,79.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Dingling
3,4,2013,3,1,3,6.0,6.0,3.0,NaN,200.0,79.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Dingling
4,5,2013,3,1,4,5.0,5.0,3.0,NaN,200.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Dingling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701275,35060,2017,2,28,19,11.0,32.0,3.0,24.0,400.0,72.0,12.5,1013.5,-16.2,0.0,NW,2.4,Wanshouxigong
701276,35061,2017,2,28,20,13.0,32.0,3.0,41.0,500.0,50.0,11.6,1013.6,-15.1,0.0,WNW,0.9,Wanshouxigong
701277,35062,2017,2,28,21,14.0,28.0,4.0,38.0,500.0,54.0,10.8,1014.2,-13.3,0.0,NW,1.1,Wanshouxigong
701278,35063,2017,2,28,22,12.0,23.0,4.0,30.0,400.0,59.0,10.5,1014.4,-12.9,0.0,NNW,1.2,Wanshouxigong
701279,35064,2017,2,28,23,13.0,19.0,4.0,38.0,600.0,49.0,8.6,1014.1,-15.9,0.0,NNE,1.3,Wanshouxigong

In [23]:
df1 = combined_df.drop_duplicates()
df1

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,3.0,NaN,200.0,82.0,-2.3,1020.8,-19.7,0.0,E,0.5,Dingling
1,2,2013,3,1,1,7.0,7.0,3.0,NaN,200.0,80.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Dingling
2,3,2013,3,1,2,5.0,5.0,3.0,2.0,200.0,79.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Dingling
3,4,2013,3,1,3,6.0,6.0,3.0,NaN,200.0,79.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Dingling
4,5,2013,3,1,4,5.0,5.0,3.0,NaN,200.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Dingling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175315,35060,2017,2,28,19,11.0,27.0,4.0,20.0,300.0,81.0,12.6,1011.9,-14.3,0.0,N,2.0,Wanliu
175316,35061,2017,2,28,20,15.0,43.0,6.0,55.0,500.0,45.0,9.4,1012.3,-11.9,0.0,WSW,1.0,Wanliu
175317,35062,2017,2,28,21,13.0,35.0,7.0,48.0,500.0,48.0,8.7,1012.8,-13.7,0.0,N,1.1,Wanliu
175318,35063,2017,2,28,22,12.0,31.0,5.0,47.0,500.0,50.0,7.8,1012.9,-12.6,0.0,NNE,1.0,Wanliu
175319,35064,2017,2,28,23,7.0,25.0,6.0,86.0,700.0,11.0,7.0,1012.6,-11.2,0.0,NE,1.1,Wanliu

In [25]:

# Save to a new CSV file
df1.to_csv("combined_output.csv", index=False)

print("All CSV files have been merged into 'combined_output.csv'.")

All CSV files have been merged into 'combined_output.csv'.

# TASK2 : EDA(EXPLORATORY DATA ANALYSIS)

## A) FUNDAMENTAL DATA UNDERSTANDING

In [26]:
df1.shape

(175320, 18)

In [28]:
df1.columns

Index(['No', 'year', 'month', 'day', 'hour', 'PM2.5', 'PM10', 'SO2', 'NO2',
       'CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station'],
      dtype='object')

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175320 entries, 0 to 175319
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   No       175320 non-null  int64
 1   year     175320 non-null  int64
 2   month    175320 non-null  int64
 3   day      175320 non-null  int64
 4   hour     175320 non-null  int64
 5   PM2.5    171873 non-null  float64
 6   PM10     172751 non-null  float64
 7   SO2      170932 non-null  float64
 8   NO2      170153 non-null  float64
 9   CO       166895 non-null  float64
 10  O3       168589 non-null  float64
 11  TEMP     175157 non-null  float64
 12  PRES     175160 non-null  float64
 13  DEWP     175154 non-null  float64
 14  RAIN     175159 non-null  float64
 15  wd       174417 non-null  object
 16  WSPM     175192 non-null  float64
 17  station  175320 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 25.4+ MB

In [30]:
selected_columns = ['No', 'year', 'month', 'day', 'hour', 'PM2.5', 'PM10', 'SO2', 'NO2','CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station']
df = df1[selected_columns]
df

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,3.0,NaN,200.0,82.0,-2.3,1020.8,-19.7,0.0,E,0.5,Dingling
1,2,2013,3,1,1,7.0,7.0,3.0,NaN,200.0,80.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Dingling
2,3,2013,3,1,2,5.0,5.0,3.0,2.0,200.0,79.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Dingling
3,4,2013,3,1,3,6.0,6.0,3.0,NaN,200.0,79.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Dingling
4,5,2013,3,1,4,5.0,5.0,3.0,NaN,200.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Dingling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175315,35060,2017,2,28,19,11.0,27.0,4.0,20.0,300.0,81.0,12.6,1011.9,-14.3,0.0,N,2.0,Wanliu
175316,35061,2017,2,28,20,15.0,43.0,6.0,55.0,500.0,45.0,9.4,1012.3,-11.9,0.0,WSW,1.0,Wanliu
175317,35062,2017,2,28,21,13.0,35.0,7.0,48.0,500.0,48.0,8.7,1012.8,-13.7,0.0,N,1.1,Wanliu
175318,35063,2017,2,28,22,12.0,31.0,5.0,47.0,500.0,50.0,7.8,1012.9,-12.6,0.0,NNE,1.0,Wanliu
175319,35064,2017,2,28,23,7.0,25.0,6.0,86.0,700.0,11.0,7.0,1012.6,-11.2,0.0,NE,1.1,Wanliu

In [33]:
# Missing values
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()

        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)

        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        print(mis_val_table)

        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})

        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns.sort_values(
        '% of Total Values', ascending=False)

        # Return the dataframe with missing information
        return mis_val_table_ren_columns

missing_values= missing_values_table(df)
missing_values.style.background_gradient(cmap='RdYlGn_r')

            0         1
No          0  0.000000
year        0  0.000000
month       0  0.000000
day         0  0.000000
hour        0  0.000000
PM2.5    3447  1.966119
PM10     2569  1.465321
SO2      4388  2.502852
NO2      5167  2.947182
CO       8425  4.805499
O3       6731  3.839265
TEMP      163  0.092973
PRES      160  0.091262
DEWP      166  0.094684
RAIN      161  0.091832
wd        903  0.515058
WSPM      128  0.073009
station     0  0.000000

In [34]:
df.describe()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,175320.000000,175320.00000,175320.000000,175320.000000,175320.000000,171873.000000,172751.000000,170932.000000,170153.000000,166895.000000,168589.000000,175157.000000,175160.000000,175154.000000,175159.000000,175192.000000
mean,17532.500000,2014.66256,6.522930,15.729637,11.500000,79.222937,102.332299,15.053055,49.138538,1217.253369,57.010496,13.591802,1011.196055,2.478606,0.063614,1.753711
std,10122.133783,1.17720,3.448713,8.800117,6.922206,80.880112,90.558393,20.710885,35.251760,1163.808540,56.389886,11.408927,10.485388,13.760064,0.800577,1.247106
min,1.000000,2013.00000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.026500,100.000000,0.214200,-16.800000,982.400000,-36.000000,0.000000,0.000000
25%,8766.750000,2014.00000,4.000000,8.000000,5.750000,20.000000,35.000000,2.000000,21.000000,500.000000,10.000000,3.200000,1002.700000,-8.900000,0.000000,0.900000
50%,17532.500000,2015.00000,7.000000,16.000000,11.500000,54.000000,80.000000,7.000000,42.000000,900.000000,45.000000,14.600000,1010.900000,3.100000,0.000000,1.400000
75%,26298.250000,2016.00000,10.000000,23.000000,17.250000,111.000000,142.000000,18.000000,70.000000,1500.000000,82.000000,23.300000,1019.500000,15.100000,0.000000,2.200000
max,35064.000000,2017.00000,12.000000,31.000000,23.000000,999.000000,999.000000,411.000000,264.000000,10000.000000,674.000000,41.400000,1042.800000,28.800000,72.500000,13.200000

In [35]:
df['solid_pollutants'] = df['PM2.5'] + df['PM10']

In [36]:
df['gas_pollutants'] = df['SO2'] + df['NO2'] + df['CO'] + df['O3']

In [37]:
print(df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'solid_pollutants', 'gas_pollutants']].head())

   PM2.5  PM10  SO2  NO2     CO    O3  solid_pollutants  gas_pollutants
0    4.0   4.0  3.0  NaN  200.0  82.0               8.0             NaN
1    7.0   7.0  3.0  NaN  200.0  80.0              14.0             NaN
2    5.0   5.0  3.0  2.0  200.0  79.0              10.0           284.0
3    6.0   6.0  3.0  NaN  200.0  79.0              12.0             NaN
4    5.0   5.0  3.0  NaN  200.0  81.0              10.0             NaN